# NumPy: A Practical Tutorial

**Topics:** Arrays · Indexing · Array Methods · Array Functions · `np.where` · Linear Algebra

---

NumPy (Numerical Python) is the core library for numerical computing in Python. It provides a fast, memory-efficient array object and a large library of mathematical functions that operate on entire arrays at once — no explicit loops needed.

**By the end of this notebook you will be able to:**
- Create and inspect NumPy arrays
- Index, slice, and filter arrays
- Use built-in array methods to summarize and transform data
- Apply mathematical functions element-wise across arrays
- Use `np.where` for conditional logic on arrays
- Solve linear systems and perform common linear algebra operations

**Prerequisites:** Basic Python — variables, lists, loops, and functions.

## Table of Contents
1. [NumPy Arrays](#1)
2. [Indexing and Slicing](#2)
3. [Array Methods](#3)
4. [Array Functions](#4)
5. [np.where and Conditional Logic](#5)
6. [Linear Algebra](#6)
7. [Exercises](#7)

---

In [2]:
import numpy as np

print('NumPy version:', np.__version__)

NumPy version: 1.26.4


<a id='1'></a>
## 1. NumPy Arrays

The central object in NumPy is the `ndarray` — an n-dimensional array of values that all share the same data type. Unlike Python lists, arrays store their data in a contiguous block of memory, which allows mathematical operations to run in compiled C code rather than the Python interpreter.

Every array has three key attributes:
- **`dtype`** — the data type of its elements (e.g., `float64`, `int32`)
- **`shape`** — a tuple of the size along each dimension
- **`ndim`** — the number of dimensions

### 1.1 Creating Arrays from Data

In [7]:
# From a Python list — the most direct route
a = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
print('Array:  ', a)
# print(type(a))
print('dtype:  ', a.dtype)    # float64 — NumPy infers the type
print('shape:  ', a.shape)    # (5,) — a 1-D array with 5 elements
print('ndim:   ', a.ndim)

print()

Array:   [1. 2. 3. 4. 5.]
dtype:   float64
shape:   (5,)
ndim:    1



In [8]:
# Integer array
b = np.array([10, 20, 30, 40])
print('Integer array:', b, '  dtype:', b.dtype)

# Force a specific dtype
c = np.array([1, 2, 3], dtype=np.float64)
print('Forced float: ', c, '  dtype:', c.dtype)

print()

Integer array: [10 20 30 40]   dtype: int64
Forced float:  [1. 2. 3.]   dtype: float64



In [9]:
# 2-D array from a nested list
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print('2-D array:\n', M)
print('shape:', M.shape)    # (3, 3) — 3 rows, 3 columns
print('ndim: ', M.ndim)

2-D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (3, 3)
ndim:  2


### 1.2 Creating Arrays from Scratch

These constructor functions are the workhorses for building grids, initial conditions, and parameter ranges.

In [11]:
# np.zeros and np.ones
print('zeros(5):    ', np.zeros(5))
print('ones(4):     ', np.ones(4))
print('ones((2,3)):\n', np.ones((2, 3)))    # shape passed as a tuple for 2-D

print()

zeros(5):     [0. 0. 0. 0. 0.]
ones(4):      [1. 1. 1. 1.]
ones((2,3)):
 [[1. 1. 1.]
 [1. 1. 1.]]



In [14]:
# np.arange — like Python range(), but returns an array
# Syntax: arange(start, stop_exclusive, step)
print('arange(0, 10, 2):  ', np.arange(0, 10, 2))
print('arange(0.0, 1.1, 0.25):', np.arange(0.0, 1.1, 0.25))

print()

arange(0, 10, 2):   [0 2 4 6 8]
arange(0.0, 1.1, 0.25): [0.   0.25 0.5  0.75 1.  ]



In [17]:

# np.linspace(start, stop, num) — N evenly spaced values between start and stop (both inclusive)
# PREFERRED over arange when you want a fixed number of points
x = np.linspace(0, 1, 6)
print('linspace(0, 1, 6):  ', x)

print()

linspace(0, 1, 6):   [0.  0.2 0.4 0.6 0.8 1. ]



In [18]:

# np.full — fill array with a constant value
print('full(4, 3.14):  ', np.full(4, 3.14))

# np.eye — identity matrix
print('eye(3):\n', np.eye(3))
#Note - here it is a nested array.

# np.logspace — logarithmically spaced values
# Useful for frequency sweeps, rate constant ranges, etc.
print('logspace(-2, 2, 5):', np.logspace(-2, 2, 5))   # 1e-2 to 1e2

full(4, 3.14):   [3.14 3.14 3.14 3.14]
eye(3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
logspace(-2, 2, 5): [1.e-02 1.e-01 1.e+00 1.e+01 1.e+02]


### 1.3 Data Types and Conversion

All elements in a NumPy array must have the same type (`dtype`). NumPy infers the type when you create an array, but you can also cast between types explicitly.

In [20]:
# Common dtypes
print('float64 (default float):', np.array([1.0, 2.0]).dtype)
print('int64   (default int):  ', np.array([1, 2]).dtype)
print('bool:                   ', np.array([True, False]).dtype)
print('complex128:             ', np.array([1+2j, 3+4j]).dtype)
print()

# Type coercion — mixing ints and floats promotes to float
mixed = np.array([1, 2.0, 3])    # int + float → float
print('Mixed [1, 2.0, 3]:', mixed, '  dtype:', mixed.dtype)

# Explicit casting with .astype()
# float to int - round vs truncate? 
a_int   = np.array([1.7, 2.3, 3.9])
a_float = a_int.astype(int)      # truncates — does NOT round
print('Truncated to int: ', a_float)
print('Rounded then int: ', np.round(a_int).astype(int))
print()

float64 (default float): float64
int64   (default int):   int64
bool:                    bool
complex128:              complex128

Mixed [1, 2.0, 3]: [1. 2. 3.]   dtype: float64
Truncated to int:  [1 2 3]
Rounded then int:  [2 2 4]



### 1.4 Vectorized Arithmetic

Arithmetic operators (`+`, `-`, `*`, `/`, `**`) on NumPy arrays act **element-wise** — the operation is applied to every pair of corresponding elements simultaneously. This is called **vectorization**. Operations between an array and a scalar extend the scalar to match the array's shape (**broadcasting**).

In [25]:
x = np.array([1.0, 2.0, 3.0, 4.0])
y = np.array([10.0, 20.0, 30.0, 40.0])

# Element-wise operations between two arrays
print('x + y =', x + y)
print('x * y =', x * y)
print('y / x =', y / x)
print('x ** 2 =', x ** 2)
print()

# Broadcasting: scalar operates on every element
print('x + 100 =', x + 100)
print('x * 2.5 =', x * 2.5)
print('x / 4   =', x / 4)
print()

x + y = [11. 22. 33. 44.]
x * y = [ 10.  40.  90. 160.]
y / x = [10. 10. 10. 10.]
x ** 2 = [ 1.  4.  9. 16.]

x + 100 = [101. 102. 103. 104.]
x * 2.5 = [ 2.5  5.   7.5 10. ]
x / 4   = [0.25 0.5  0.75 1.  ]



In [31]:
# Speed comparison — Vectorized vs. Python loop
import time
n = 1_000_000
data_list = list(range(n))
data_arr  = np.arange(n, dtype=float)

#python loop
t0 = time.perf_counter()
_ = [v ** 2 for v in data_list]
t_loop = time.perf_counter() - t0

#numpy array
t0 = time.perf_counter()
_ = data_arr ** 2
t_vec = time.perf_counter() - t0

print(f'Python loop: {t_loop*1000:.1f} ms')
print(f'NumPy array: {t_vec*1000:.1f} ms')
print(f'Speedup:     {t_loop/t_vec:.0f}×')

Python loop: 33.0 ms
NumPy array: 7.4 ms
Speedup:     4×


### 1.5 Broadcasting Rules

Broadcasting allows arrays of different shapes to work together. NumPy compares shapes element-by-element from the trailing dimension. Dimensions are compatible if they are equal or one of them is 1. The classic example: adding a 1-D vector to each row or column of a 2-D matrix.

In [34]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]], dtype=float)
print(A)
# print(A+[5])

# Add a row vector to every row of A (shape (3,) broadcasts with (3,3))
row = np.array([10, 20, 30])
print('A + row (add to each row):\n', A + row)

print()


# Add a column vector to every column of A (shape (3,1) broadcasts with (3,3))
# defining columns here vs rows.
col = np.array([[100], [200], [300]])    # shape (3, 1)
print('A + col (add to each column):\n', A + col)

print()

# Outer product using broadcasting — build a multiplication table
r = np.arange(1, 5).reshape(4, 1)     # column: shape (4, 1)
c = np.arange(1, 5).reshape(1, 4)     # row:    shape (1, 4)
print('4×4 multiplication table:\n', r * c)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
A + row (add to each row):
 [[11. 22. 33.]
 [14. 25. 36.]
 [17. 28. 39.]]

A + col (add to each column):
 [[101. 102. 103.]
 [204. 205. 206.]
 [307. 308. 309.]]

4×4 multiplication table:
 [[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


<a id='2'></a>
## 2. Indexing and Slicing

NumPy extends Python's slice notation to multiple dimensions and adds **Boolean indexing** and **fancy indexing** (indexing with an array of indices). These are the tools you use to extract, filter, and update data.

### 2.1 Basic Indexing — 1-D Arrays

In [35]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

print('Full array:     ', a)
print('a[0]:           ', a[0])       # first element
print('a[-1]:          ', a[-1])      # last element
print('a[2]:           ', a[2])       # index 2

print()

# Slicing: a[start : stop : step]  (stop is exclusive)
print('a[1:4]:         ', a[1:4])     # elements at index 1, 2, 3
print('a[:3]:          ', a[:3])      # first three elements
print('a[6:]:          ', a[6:])      # from index 6 to end
print('a[-3:]:         ', a[-3:])     # last three elements
print('a[::2]:         ', a[::2])     # every second element
print('a[::-1]:        ', a[::-1])    # reversed

print()

# Slices are VIEWS — modifying a slice modifies the original array
b = a[2:5]
b[0] = 999
print('After modifying slice: a =', a)    # a[2] changed!

# Use .copy() to get an independent copy
a = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])  # reset
c = a[2:5].copy()
c[0] = 999
print('After modifying copy:  a =', a)    # a unchanged

Full array:      [10 20 30 40 50 60 70 80 90]
a[0]:            10
a[-1]:           90
a[2]:            30

a[1:4]:          [20 30 40]
a[:3]:           [10 20 30]
a[6:]:           [70 80 90]
a[-3:]:          [70 80 90]
a[::2]:          [10 30 50 70 90]
a[::-1]:         [90 80 70 60 50 40 30 20 10]

After modifying slice: a = [ 10  20 999  40  50  60  70  80  90]
After modifying copy:  a = [10 20 30 40 50 60 70 80 90]


### 2.2 Indexing 2-D Arrays

For a 2-D array, indexing is `M[row, col]`. Slicing works independently along each axis.

In [ ]:
M = np.array([[1,  2,  3,  4],
              [5,  6,  7,  8],
              [9, 10, 11, 12],
              [13,14, 15, 16]])
print('Matrix M:\n', M)
print()

# Single element: M[row, col]
print('M[1, 2]:         ', M[1, 2])       # row 1, col 2 → 7
print('M[-1, -1]:       ', M[-1, -1])     # bottom-right → 16
print()

# Entire row / column
print('Row 0:           ', M[0, :])       # first row   (: = all columns)
print('Column 2:        ', M[:, 2])       # third column (: = all rows)
print()

# Sub-matrix (block)
print('Top-left 2×2:\n', M[:2, :2])
print('Bottom-right 2×2:\n', M[2:, 2:])
print('Middle 2×2:\n', M[1:3, 1:3])
print()

# Strided slicing
print('Every other row, every other col:\n', M[::2, ::2])

Matrix M:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

M[1, 2]:          7
M[-1, -1]:        16

Row 0:            [1 2 3 4]
Column 2:         [ 3  7 11 15]

Top-left 2×2:
 [[1 2]
 [5 6]]
Bottom-right 2×2:
 [[11 12]
 [15 16]]
Middle 2×2:
 [[ 6  7]
 [10 11]]

Every other row, every other col:
 [[ 1  3]
 [ 9 11]]


### 2.3 Boolean Indexing

A comparison on an array returns a Boolean array of the same shape. Passing this Boolean array as an index selects only the elements where it is `True`. This is the primary tool for filtering data.

In [38]:
x = np.array([3, -1, 7, -4, 2, 9, -2, 5, 0, 6])

# A comparison produces a Boolean array
mask = x > 0
print('x:       ', x)
print('x > 0:   ', mask)

# Use the mask to filter
print('Positive values:', x[mask])
print('Negative values:', x[x < 0])
print()

x:        [ 3 -1  7 -4  2  9 -2  5  0  6]
x > 0:    [ True False  True False  True  True False  True False  True]
Positive values: [3 7 2 9 5 6]
Negative values: [-1 -4 -2]



In [40]:
# Compound conditions — use & (and), | (or), ~ (not)
# Must wrap each condition in parentheses!
between = (x >= 2) & (x <= 6)
print('Values in [2, 6]:', x[between])
print('Values outside (2,6):', x[~between])
print()

# Boolean indexing also works on 2-D arrays
M2 = np.arange(1, 13).reshape(3, 4)
print('M2:\n', M2)
print('Elements > 6:', M2[M2 > 6])      # returns a 1-D array of matching elements
print()

# Assignment through a Boolean mask
data = np.array([1.0, -0.5, 3.2, -1.1, 2.7])
data[data < 0] = 0.0     # clip negatives to zero in place
print('After zeroing negatives:', data)

Values in [2, 6]: [3 2 5 6]
Values outside (2,6): [-1  7 -4  9 -2  0]

M2:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Elements > 6: [ 7  8  9 10 11 12]

After zeroing negatives: [1.  0.  3.2 0.  2.7]


### 2.4 Fancy Indexing

You can index an array with another array of integers to select arbitrary elements — not just contiguous slices. This is called **fancy indexing**. Unlike slices, fancy indexing always returns a **copy**.

In [45]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])

# Select specific elements by index
idx = np.array([0, 2, 5, 7])
print('Selected elements:', a[idx])

# Repeat or reorder elements
print('Reordered:', a[[3, 0, 6, 1]])
print()

# Useful pattern: find the top-k values
scores = np.array([72, 85, 91, 64, 88, 79, 95, 83])
top3_idx = np.argsort(scores)[-3:]          # indices of 3 largest
print('Top 3 scores:', scores[top3_idx])
print('Top 3 indices:', top3_idx)

# Sort in descending order
sorted_desc = scores[np.argsort(scores)[::-1]]
print('All scores, descending:', sorted_desc)

print()

# Fancy indexing on 2-D: select specific rows
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10,11,12]])
row_idx = [0, 2, 3]      # rows 0, 2, 3
print('Selected rows:\n', M[row_idx])

Selected elements: [10 30 60 80]
Reordered: [40 10 70 20]

Top 3 scores: [88 91 95]
Top 3 indices: [4 2 6]
All scores, descending: [95 91 88 85 83 79 72 64]

Selected rows:
 [[ 1  2  3]
 [ 7  8  9]
 [10 11 12]]


<a id='3'></a>
## 3. Array Methods

NumPy arrays come with methods attached directly to the object — called as `a.method()`. These cover aggregation, sorting, reshaping, and type conversion. Many accept an `axis` argument to operate along rows or columns of a 2-D array.

### 3.1 Aggregation Methods

In [49]:
a = np.array([4.0, 7.0, 2.0, 9.0, 1.0, 6.0, 3.0, 8.0, 5.0])

print('Array:    ', a)
print('sum():    ', a.sum())
print('mean():   ', a.mean())
print('std():    ', a.std())          # population std by default
print('var():    ', a.var())
print('min():    ', a.min())
print('max():    ', a.max())
print('argmin(): ', a.argmin())      # INDEX of minimum
print('argmax(): ', a.argmax())      # INDEX of maximum
print('cumsum(): ', a.cumsum())
print('cumprod():', a.cumprod().round(1))
print('prod():   ', a.prod())

Array:     [4. 7. 2. 9. 1. 6. 3. 8. 5.]
sum():     45.0
mean():    5.0
std():     2.581988897471611
var():     6.666666666666667
min():     1.0
max():     9.0
argmin():  4
argmax():  3
cumsum():  [ 4. 11. 13. 22. 23. 29. 32. 40. 45.]
cumprod(): [4.0000e+00 2.8000e+01 5.6000e+01 5.0400e+02 5.0400e+02 3.0240e+03
 9.0720e+03 7.2576e+04 3.6288e+05]
prod():    362880.0


In [53]:
# The axis argument — essential for 2-D arrays
# axis=0 → operate DOWN the rows (result has one value per COLUMN)
# axis=1 → operate ACROSS the columns (result has one value per ROW)

M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]], dtype=float)

print('Matrix M:\n', M)
print()
print('Sum of entire matrix:      ', M.sum())
print('Column sums (axis=0):      ', M.sum(axis=0))    # [1+4+7, 2+5+8, 3+6+9]
print('Row sums    (axis=1):      ', M.sum(axis=1))    # [1+2+3, 4+5+6, 7+8+9]
print('Column means (axis=0):     ', M.mean(axis=0))
print('Row means    (axis=1):     ', M.mean(axis=1))
print('Column max   (axis=0):     ', M.max(axis=0))
print('Row argmax   (axis=1):     ', M.argmax(axis=1))  # col index of max in each row

Matrix M:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Sum of entire matrix:       45.0
Column sums (axis=0):       [12. 15. 18.]
Row sums    (axis=1):       [ 6. 15. 24.]
Column means (axis=0):      [4. 5. 6.]
Row means    (axis=1):      [2. 5. 8.]
Column max   (axis=0):      [7. 8. 9.]
Row argmax   (axis=1):      [2 2 2]


### 3.2 Sorting and Searching

In [56]:
# Try it out! 

a = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])

# sort() returns a sorted copy; does not modify the original
print('Original:      ', a)
print('Sorted:        ', np.sort(a))
print('Descending:    ', np.sort(a)[::-1])

# argsort() returns the indices that would sort the array
idx = np.argsort(a)
print('argsort:       ', idx)
print('a[argsort]:    ', a[idx])      # same as np.sort(a)

print()

# searchsorted — find where a value would be inserted (for sorted arrays)
s = np.array([1, 3, 5, 7, 9, 11])
print('searchsorted(s, 6):   ', np.searchsorted(s, 6))    # insert 6 at index 3
print('searchsorted(s, [4,8]):', np.searchsorted(s, [4, 8]))
print()

# unique — find unique values
print('Unique values:', np.unique(a))

# unique with counts
vals, counts = np.unique(a, return_counts=True)
print('Value : Count')
for v, c in zip(vals, counts):
    print(f'  {v}   :   {c}')

Original:       [3 1 4 1 5 9 2 6 5 3]
Sorted:         [1 1 2 3 3 4 5 5 6 9]
Descending:     [9 6 5 5 4 3 3 2 1 1]
argsort:        [1 3 6 0 9 2 4 8 7 5]
a[argsort]:     [1 1 2 3 3 4 5 5 6 9]

searchsorted(s, 6):    3
searchsorted(s, [4,8]): [2 4]

Unique values: [1 2 3 4 5 6 9]
Value : Count
  1   :   2
  2   :   1
  3   :   2
  4   :   1
  5   :   2
  6   :   1
  9   :   1


### 3.3 Reshaping and Stacking

In [60]:
# reshape — change dimensions without copying data
# Total number of elements must stay the same
a = np.arange(12)
print('Original (12,):     ', a)
print('Reshaped (3, 4):\n', a.reshape(3, 4))
print('Reshaped (2, 6):\n', a.reshape(2, 6))

# flatten() — return a 1-D copy
M = a.reshape(3, 4)
print('Flattened:          ', M.flatten())

# ravel() — return a 1-D VIEW (faster, no copy if possible)
print('Ravelled:           ', M.ravel())
print()

# Stacking arrays
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print('vstack (row-wise):\n', np.vstack([x, y]))   # shape (2, 3)
print('hstack (col-wise):  ', np.hstack([x, y]))   # shape (6,)
print('column_stack:\n', np.column_stack([x, y]))  # shape (3, 2)
print()

# Transpose
M2 = np.array([[1, 2, 3],
               [4, 5, 6]])
print('M2 shape:', M2.shape, 'M2.T shape:', M2.T.shape)
print('M2.T:\n', M2.T)

Original (12,):      [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped (3, 4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Reshaped (2, 6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Flattened:           [ 0  1  2  3  4  5  6  7  8  9 10 11]
Ravelled:            [ 0  1  2  3  4  5  6  7  8  9 10 11]

vstack (row-wise):
 [[1 2 3]
 [4 5 6]]
hstack (col-wise):   [1 2 3 4 5 6]
column_stack:
 [[1 4]
 [2 5]
 [3 6]]

M2 shape: (2, 3) M2.T shape: (3, 2)
M2.T:
 [[1 4]
 [2 5]
 [3 6]]


<a id='4'></a>
## 4. Array Functions

NumPy provides a large library of **universal functions** (ufuncs) — functions that apply element-wise to arrays. They are called as `np.function(array)` rather than as array methods. This section covers mathematical functions, statistical functions, and set operations.

### 4.1 Mathematical Functions

In [66]:
x = np.array([0.0, 0.25, 0.5, 0.75, 1.0])

# Exponential and logarithm
print('exp(x):    ', np.exp(x).round(4))
print('log(x+0.1):', np.log(x + 0.1).round(4))    # natural log
print('log2(8):   ', np.log2(8))
print('log10(100):', np.log10(100))
print()

# Trigonometry (angles in RADIANS)
theta = np.linspace(0, 2 * np.pi, 5)
print('sin(θ):    ', np.sin(theta).round(4))
print('cos(θ):    ', np.cos(theta).round(4))
print('tan(π/4):  ', np.tan(np.pi / 4).round(6))   # should be 1.0

# Degrees / radians conversion
print('deg2rad(180):', np.deg2rad(180))   # = π
print('rad2deg(π):  ', np.rad2deg(np.pi))
print()

# Power, root, absolute value
a = np.array([1.0, 4.0, 9.0, 16.0, 25.0])
print('sqrt:   ', np.sqrt(a))
print('cbrt:   ', np.cbrt(a).round(4))    # cube root
print('abs:    ', np.abs(np.array([-3, -1, 0, 2, -5])))
print('sign:   ', np.sign(np.array([-3, 0, 5])))

exp(x):     [1.     1.284  1.6487 2.117  2.7183]
log(x+0.1): [-2.3026 -1.0498 -0.5108 -0.1625  0.0953]
log2(8):    3.0
log10(100): 2.0

sin(θ):     [ 0.  1.  0. -1. -0.]
cos(θ):     [ 1.  0. -1. -0.  1.]
tan(π/4):   1.0
deg2rad(180): 3.141592653589793
rad2deg(π):   180.0

sqrt:    [1. 2. 3. 4. 5.]
cbrt:    [1.     1.5874 2.0801 2.5198 2.924 ]
abs:     [3 1 0 2 5]
sign:    [-1  0  1]


In [68]:
# Rounding functions
vals = np.array([-2.7, -1.5, -0.3, 0.3, 1.5, 2.7])

print('Values:  ', vals)
print('round:   ', np.round(vals))      # round to nearest even (banker's rounding)
print('floor:   ', np.floor(vals))      # round DOWN toward -∞
print('ceil:    ', np.ceil(vals))       # round UP toward +∞
print('trunc:   ', np.trunc(vals))      # truncate toward zero
print()

# Clip — enforce lower and/or upper bounds
data = np.array([-3, 0, 5, 12, -1, 8, 20])
print('Original:         ', data)
print('clip(0, 10):      ', np.clip(data, 0, 10))
print('clip(None, 5):    ', np.clip(data, None, 5))   # upper bound only

Values:   [-2.7 -1.5 -0.3  0.3  1.5  2.7]
round:    [-3. -2. -0.  0.  2.  3.]
floor:    [-3. -2. -1.  0.  1.  2.]
ceil:     [-2. -1. -0.  1.  2.  3.]
trunc:    [-2. -1. -0.  0.  1.  2.]

Original:          [-3  0  5 12 -1  8 20]
clip(0, 10):       [ 0  0  5 10  0  8 10]
clip(None, 5):     [-3  0  5  5 -1  5  5]


### 4.2 Statistical Functions

In [79]:
# random number generator - 
rng = np.random.default_rng(seed=42)
data = rng.normal(loc=50.0, scale=10.0, size=100)   # 100 samples, μ=50, σ=10

print('=== Descriptive Statistics ===')
print(f'Count:       {len(data)}')
print(f'Mean:        {np.mean(data):.4f}')
print(f'Median:      {np.median(data):.4f}')
print(f'Std (pop):   {np.std(data):.4f}')
print(f'Variance:    {np.var(data):.4f}')
print(f'Min:         {np.min(data):.4f}')
print(f'Max:         {np.max(data):.4f}')

print()

# Percentiles and quantiles
print(f'25th pct:    {np.percentile(data, 25):.4f}')
print(f'75th pct:    {np.percentile(data, 75):.4f}')

# Multiple percentiles at once
pcts = np.percentile(data, [0, 10, 25, 50, 75, 90, 100])
print('Percentiles [0,10,25,50,75,90,100]:', pcts.round(2))

print()

=== Descriptive Statistics ===
Count:       100
Mean:        49.4973
Median:      49.9785
Std (pop):   7.7278
Variance:    59.7195
Min:         30.4896
Max:         71.4165

25th pct:    44.5610
75th pct:    55.3502
Percentiles [0,10,25,50,75,90,100]: [30.49 39.51 44.56 49.98 55.35 58.59 71.42]



### 4.3 Set Operations and Comparison Functions

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([4, 5, 6, 7, 8, 9])

print('a:', a)
print('b:', b)
print('Union:        ', np.union1d(a, b))
print('Intersection: ', np.intersect1d(a, b))
print('Difference a-b:', np.setdiff1d(a, b))
print('Difference b-a:', np.setdiff1d(b, a))
print('In both?      ', np.in1d(a, b))     # Boolean: is each element of a in b?

print()

# Element-wise comparison functions
x = np.array([1.0, 2.0, np.nan, 4.0])
y = np.array([1.0, 3.0, np.nan, 4.0])

# WARNING: nan != nan with the == operator
print('x == y (with nan):', x == y)           # nan comparison is always False
print('isnan(x):         ', np.isnan(x))
print('isfinite(x):      ', np.isfinite(x))

# allclose — compare arrays with a tolerance (nan-safe with equal_nan=True)
p = np.array([1.0, 2.0, 3.0])
q = np.array([1.0, 2.0 + 1e-10, 3.0])
print('\nallclose(p, q): ', np.allclose(p, q))   # True — within tolerance
print('array_equal(p, q):', np.array_equal(p, q)) # False — exact comparison

# any() and all() on Boolean conditions
data = np.array([2, -1, 5, 3, -2, 8])
print('\nAny negative?  ', np.any(data < 0))
print('All positive?  ', np.all(data > 0))
print('Count negative:', np.sum(data < 0))

<a id='5'></a>
## 5. `np.where` and Conditional Logic

`np.where` is the NumPy equivalent of an element-wise `if-else` expression. It is the key tool for applying conditional transformations to arrays without writing a Python loop.

### 5.1 `np.where(condition, x, y)`

Where `condition` is `True`, return the corresponding element from `x`; where it is `False`, return the corresponding element from `y`.

In [80]:
a = np.array([-3, -1, 0, 2, 5, -2, 8, -4, 3])

# Replace negatives with 0 (like np.clip(a, 0, None))
result = np.where(a > 0, a, 0)
print('Original:           ', a)
print('Negatives → 0:      ', result)

print()

# Replace with computed values
# Absolute value: where a >= 0 keep a, else use -a
abs_val = np.where(a >= 0, a, -a)
print('Manual abs value:   ', abs_val)
print('np.abs for check:   ', np.abs(a))

print()

# Label values: positive → 1, negative → -1, zero → 0
# Chain np.where calls for multiple conditions
labels = np.where(a > 0, 1, np.where(a < 0, -1, 0))
print('Signs:              ', labels)
print('np.sign for check:  ', np.sign(a))

print()

# Both x and y can be arrays
x = np.array([10, 20, 30, 40, 50])
y = np.array([1,  2,  3,  4,  5])
cond = np.array([True, False, True, False, True])
print('where(cond, x, y):', np.where(cond, x, y))   # [10, 2, 30, 4, 50]

Original:            [-3 -1  0  2  5 -2  8 -4  3]
Negatives → 0:       [0 0 0 2 5 0 8 0 3]

Manual abs value:    [3 1 0 2 5 2 8 4 3]
np.abs for check:    [3 1 0 2 5 2 8 4 3]

Signs:               [-1 -1  0  1  1 -1  1 -1  1]
np.sign for check:   [-1 -1  0  1  1 -1  1 -1  1]

where(cond, x, y): [10  2 30  4 50]


### 5.2 `np.where(condition)` — Finding Indices

When called with only a condition and no `x` or `y`, `np.where` returns the **indices** where the condition is `True`. This is equivalent to `np.nonzero(condition)`.

In [ ]:
a = np.array([3, -1, 7, -4, 2, 9, -2, 5, 0, 6])

# Returns a tuple of arrays — one per dimension
idx = np.where(a > 0)
print('Condition a > 0')
print('Indices where True:', idx[0])       # unpack the tuple
print('Values at those indices:', a[idx])

print()

# 2-D: returns row indices and column indices
M = np.array([[1,  -2,  3],
              [-4,  5, -6],
              [7,  -8,  9]])

rows, cols = np.where(M > 0)
print('Matrix M:\n', M)
print('\nPositive elements:')
for r, c in zip(rows, cols):
    print(f'  M[{r},{c}] = {M[r, c]}')
print()

# argwhere — same as np.where but returns (N, ndim) array of coordinates
coords = np.argwhere(M > 0)
print('argwhere (coordinates of positives):\n', coords)

Condition a > 0
Indices where True: [0 2 4 5 7 9]
Values at those indices: [3 7 2 9 5 6]

Matrix M:
 [[ 1 -2  3]
 [-4  5 -6]
 [ 7 -8  9]]

Positive elements:
  M[0,0] = 1
  M[0,2] = 3
  M[1,1] = 5
  M[2,0] = 7
  M[2,2] = 9

argwhere (coordinates of positives):
 [[0 0]
 [0 2]
 [1 1]
 [2 0]
 [2 2]]


### 5.3 Piecewise Functions with `np.where`

A piecewise function applies a different formula in different regions. Nested `np.where` calls or `np.select` handle this cleanly.

In [85]:
x = np.linspace(-3, 3, 13)

# Piecewise function:
#   f(x) = x²        if x < -1
#   f(x) = 0         if -1 <= x <= 1
#   f(x) = x² - 1   if x > 1

# Method 1: nested np.where
f = np.where(x < -1, x**2,
     np.where(x > 1,  x**2 - 1, 0.0))

print('x:  ', x.round(2))
print('f:  ', f.round(3))

print()

# Method 2: np.select — cleaner for many conditions
conditions = [x < -1, (x >= -1) & (x <= 1), x > 1]
choices    = [x**2,   0.0,  x**2 - 1]
f2 = np.select(conditions, choices, default=0.0)

print('np.select result matches:', np.allclose(f, f2))

print()

# Method 3: np.piecewise — explicit domain partitioning
f3 = np.piecewise(x,
                  [x < -1, (x >= -1) & (x <= 1), x > 1],
                  [lambda v: v**2, 0.0, lambda v: v**2 - 1])
print('np.piecewise result matches:', np.allclose(f, f3))

x:   [-3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.   2.5  3. ]
f:   [9.   6.25 4.   2.25 0.   0.   0.   0.   0.   1.25 3.   5.25 8.  ]

np.select result matches: True

np.piecewise result matches: True


<a id='6'></a>
## 6. Linear Algebra

The `numpy.linalg` submodule provides the core linear algebra operations: solving linear systems, matrix decompositions, eigenvalues, and norms. These underpin numerical methods across science and engineering.

### 6.1 Matrix Multiplication

In [92]:
A = np.array([[1, 2],
              [3, 4]], dtype=float)
B = np.array([[5, 6],
              [7, 8]], dtype=float)
v = np.array([1.0, 2.0])

# The @ operator — matrix multiplication (Python 3.5+)
print('A @ B (matrix × matrix):\n', A @ B)
print('A @ v (matrix × vector):', A @ v)

print()

# CAUTION: * is element-wise, not matrix multiply!
print('A * B (element-wise):\n', A * B)   # NOT matrix multiplication

print()

# Dot product of two vectors
u = np.array([1.0, 2.0, 3.0])
w = np.array([4.0, 5.0, 6.0])
print('u · w (dot product):', np.dot(u, w))    # 1*4 + 2*5 + 3*6 = 32
print('u @ w  (same):       ', u @ w)

# Outer product
print('Outer product:\n', np.outer(u[:3], w[:3]))

A @ B (matrix × matrix):
 [[19. 22.]
 [43. 50.]]
A @ v (matrix × vector): [ 5. 11.]

A * B (element-wise):
 [[ 5. 12.]
 [21. 32.]]

u · w (dot product): 32.0
u @ w  (same):        32.0
Outer product:
 [[ 4.  5.  6.]
 [ 8. 10. 12.]
 [12. 15. 18.]]


### 6.2 Solving Linear Systems — `np.linalg.solve`

The most common linear algebra task: solve $\mathbf{A}\mathbf{x} = \mathbf{b}$ for $\mathbf{x}$. `np.linalg.solve` is numerically stable (uses LU factorization with partial pivoting). **Do not invert A** — solving is faster and more accurate.

In [94]:
# System of 3 equations in 3 unknowns:
#   2x + y - z  =  8
#  -3x - y + 2z = -11
#  -2x + y + 2z = -3

A = np.array([[ 2,  1, -1],
              [-3, -1,  2],
              [-2,  1,  2]], dtype=float)

b = np.array([8.0, -11.0, -3.0])

x = np.linalg.solve(A, b)
print('Solution x:', x)    # should be [2, 3, -1]

# Verify: A @ x should reproduce b
print('A @ x =', A @ x)
print('b     =', b)
print('Residual norm:', np.linalg.norm(A @ x - b))
print()

# Why not use the inverse?
x_inv = np.linalg.inv(A) @ b    # works, but slower and less accurate
print('Via inverse:  ', x_inv)
print('Via solve:    ', x)
print('(Both correct here, but solve is always preferred)')
print()

# Solve for multiple right-hand sides at once
# Each column of B is a separate RHS vector
B_rhs = np.array([[ 8.0,  1.0],
                  [-11.0, 2.0],
                  [-3.0,  6.0]])
X = np.linalg.solve(A, B_rhs)   # solves both systems simultaneously
print('Solutions for two RHS vectors:\n', X)

Solution x: [ 2.  3. -1.]
A @ x = [  8. -11.  -3.]
b     = [  8. -11.  -3.]
Residual norm: 9.930136612989092e-16

Via inverse:   [ 2.  3. -1.]
Via solve:     [ 2.  3. -1.]
(Both correct here, but solve is always preferred)

Solutions for two RHS vectors:
 [[ 2.00000000e+00  4.00000000e+00]
 [ 3.00000000e+00 -1.59872116e-15]
 [-1.00000000e+00  7.00000000e+00]]


### 6.3 Least Squares — `np.linalg.lstsq`

When the system is **overdetermined** (more equations than unknowns — the typical case in data fitting), there is no exact solution. `lstsq` finds the $\mathbf{x}$ that minimizes $\|\mathbf{A}\mathbf{x} - \mathbf{b}\|^2$. This is the foundation of linear regression.

In [ ]:
# Linear regression: fit y = β₀ + β₁ x to noisy data
rng = np.random.default_rng(seed=0)

x_obs = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0])
y_obs = 2.5 + 1.8 * x_obs + rng.normal(0, 0.5, size=len(x_obs))  # true: β₀=2.5, β₁=1.8

# Design matrix: column of ones (intercept) + column of x
A_design = np.column_stack([np.ones_like(x_obs), x_obs])  # shape (8, 2)
print('Design matrix:\n', A_design)

# Least squares
coeffs, residuals, rank, sv = np.linalg.lstsq(A_design, y_obs, rcond=None)
beta0, beta1 = coeffs

print(f'\nFitted coefficients:')
print(f'  β₀ (intercept) = {beta0:.4f}  (true: 2.5)')
print(f'  β₁ (slope)     = {beta1:.4f}  (true: 1.8)')

# R² — coefficient of determination
y_pred   = A_design @ coeffs
ss_res   = np.sum((y_obs - y_pred) ** 2)
ss_tot   = np.sum((y_obs - y_obs.mean()) ** 2)
r_squared = 1 - ss_res / ss_tot
print(f'  R²             = {r_squared:.4f}')

print()

# Polynomial regression: fit y = β₀ + β₁ x + β₂ x²
# Build design matrix using np.vander or manually
A_poly = np.column_stack([np.ones_like(x_obs), x_obs, x_obs**2])
coeffs_poly, _, _, _ = np.linalg.lstsq(A_poly, y_obs, rcond=None)
print('Quadratic fit coefficients:', coeffs_poly.round(4))

### 6.4 Matrix Decompositions

Decompositions factor a matrix into simpler components that reveal its structure. The three most important for data analysis are:
- **LU** — general linear systems (used internally by `solve`)
- **QR** — numerically stable least squares
- **SVD** — dimensionality reduction, rank, pseudo-inverse, PCA

In [ ]:
A = np.array([[4.0, 3.0],
              [6.0, 3.0]])

# --- QR decomposition: A = Q @ R ---
# Q = orthogonal matrix, R = upper triangular
Q, R = np.linalg.qr(A)
print('QR decomposition of A:')
print('Q:\n', Q.round(4))
print('R:\n', R.round(4))
print('Q @ R ≈ A:', np.allclose(Q @ R, A))
print('Q is orthogonal (Q^T Q = I):', np.allclose(Q.T @ Q, np.eye(2)))

print()

# --- SVD: A = U @ diag(s) @ V^T ---
# U, V = orthogonal matrices of left/right singular vectors
# s = singular values (non-negative, descending order)
U, s, Vt = np.linalg.svd(A)
print('SVD of A:')
print('U:\n', U.round(4))
print('Singular values s:', s.round(4))
print('V^T:\n', Vt.round(4))

# Reconstruct A from SVD
A_reconstructed = U @ np.diag(s) @ Vt
print('Reconstruction error:', np.linalg.norm(A - A_reconstructed))

# Matrix rank from SVD: number of non-negligible singular values
rank = np.sum(s > 1e-10)
print('Matrix rank:', rank)

### 6.5 Eigenvalues and Eigenvectors

In [ ]:
# eig — general square matrix (eigenvalues may be complex)
A = np.array([[4.0, 1.0],
              [2.0, 3.0]])

eigenvalues, eigenvectors = np.linalg.eig(A)
print('Matrix A:\n', A)
print('Eigenvalues:', eigenvalues)
print('Eigenvectors (columns):\n', eigenvectors.round(4))

# Verify: A @ v = λ * v for each eigenpair
for i, lam in enumerate(eigenvalues):
    v = eigenvectors[:, i]
    check = np.allclose(A @ v, lam * v)
    print(f'  λ={lam:.2f}: A·v = λ·v? {check}')

print()

# eigh — symmetric/Hermitian matrix (eigenvalues always real)
# Faster and more accurate than eig for symmetric matrices
S = np.array([[5.0, 2.0, 1.0],
              [2.0, 4.0, 3.0],
              [1.0, 3.0, 6.0]])

lam, V = np.linalg.eigh(S)   # eigenvalues returned in ASCENDING order
print('Symmetric matrix S:\n', S)
print('Eigenvalues (ascending):', lam.round(4))
print('Eigenvectors:\n', V.round(4))
print('V is orthogonal:', np.allclose(V @ V.T, np.eye(3)))

### 6.6 Norms, Determinant, and Condition Number

In [ ]:
v = np.array([3.0, -4.0, 0.0])
A = np.array([[1.0, 2.0],
              [3.0, 4.0]])

# --- Vector norms ---
print('Vector v:', v)
print('L2 norm (Euclidean):  ', np.linalg.norm(v))          # default
print('L1 norm (Manhattan):  ', np.linalg.norm(v, ord=1))
print('L∞ norm (max abs):    ', np.linalg.norm(v, ord=np.inf))

print()

# --- Matrix norms ---
print('Matrix Frobenius norm:', np.linalg.norm(A, 'fro'))   # default
print('Matrix 2-norm (max sv):', np.linalg.norm(A, ord=2))

print()

# --- Determinant ---
print('det(A):', np.linalg.det(A))

# Singular matrix has det = 0 and cannot be inverted
B = np.array([[2.0, 4.0],
              [1.0, 2.0]])    # row 2 = 0.5 * row 1
print('det(B):', np.linalg.det(B))   # should be ~0

print()

# --- Condition number ---
# Measures sensitivity of the solution to small perturbations in A or b
# A large condition number means the system is ill-conditioned
# Rule of thumb: cond > 1e12 → results unreliable in float64
print('cond(A):', np.linalg.cond(A).round(4))

A_ill = np.array([[1.0,    1.0   ],
                  [1.0,    1.0001]])    # nearly singular
print('cond(A_ill):', np.linalg.cond(A_ill).round(1))   # very large

### 6.7 Pseudo-inverse and Rank-Deficient Systems

In [ ]:
# The Moore-Penrose pseudo-inverse handles non-square and rank-deficient matrices
# For full-rank square A: pinv(A) = inv(A)
# For overdetermined A (more rows than columns): pinv(A) = (A^T A)^{-1} A^T  (least squares)

# Overdetermined system — more data points than parameters
A = np.array([[1, 0],
              [0, 1],
              [1, 1],
              [1, 2]])   # shape (4, 2) — 4 equations, 2 unknowns
b = np.array([1.0, 2.0, 3.5, 5.0])

# Pseudo-inverse solution (minimizes ||Ax - b||)
A_pinv = np.linalg.pinv(A)
x_pinv = A_pinv @ b
print('Pseudo-inverse solution:', x_pinv.round(4))

# Same result as lstsq
x_lstsq, _, _, _ = np.linalg.lstsq(A, b, rcond=None)
print('lstsq solution:         ', x_lstsq.round(4))
print('Agreement:', np.allclose(x_pinv, x_lstsq))

print()

# Trace (sum of diagonal elements) — equals sum of eigenvalues
M = np.array([[1.0, 2.0, 3.0],
              [4.0, 5.0, 6.0],
              [7.0, 8.0, 9.0]])
print('Trace(M):', np.trace(M))   # 1 + 5 + 9 = 15
print('Diagonal:', np.diag(M))    # extract diagonal elements
print('np.diag([1,2,3]):\n', np.diag([1, 2, 3]))  # build diagonal matrix

<a id='7'></a>
## 7. Exercises

Each problem is self-contained. Solve them using NumPy — avoid Python loops unless the problem explicitly asks for comparison.

---

**Exercise 1 — Array Creation and Vectorized Arithmetic**  
a. Create an array of the first 20 positive odd integers using `np.arange`.  
b. Compute the element-wise square root of the array from (a) using a single NumPy expression.  
c. Create a 5×5 matrix where entry (i, j) equals i + j (zero-indexed). *(Hint: use broadcasting with `reshape`.)*  
d. Normalize the matrix from (c) so that each row sums to 1.

---

**Exercise 2 — Indexing and Filtering**  
Generate the following array:  
```python
rng = np.random.default_rng(42)
data = rng.integers(-10, 11, size=(6, 6))  # integers in [-10, 10]
```
a. Extract all values in the bottom-right 3×3 sub-matrix.  
b. Using Boolean indexing, extract all **positive even** values from the full array.  
c. Replace all negative values with their absolute values using a single `np.where` call (no loops).  
d. Find the row and column indices of the three largest values in the modified array.

---

**Exercise 3 — Array Methods and Statistics**  
You have a 10×4 data matrix (10 observations, 4 variables):  
```python
rng = np.random.default_rng(7)
X = rng.normal(loc=[10, 50, 0, 100], scale=[2, 5, 1, 20], size=(10, 4))
```
a. Compute the mean and standard deviation of each variable (column) using a single `axis` argument.  
b. Standardize the matrix (subtract the column mean, divide by column std) using broadcasting — no loops.  
c. Verify that each column of the standardized matrix has mean ≈ 0 and std ≈ 1.  
d. For each observation (row), identify which variable has the largest absolute value in the standardized matrix.

---

**Exercise 4 — `np.where` and Piecewise Definitions**  
Define the function on the domain $x \in [-4, 4]$ with 200 points:

$$f(x) = \begin{cases} -x^2 & x < -1 \\ x^3 & -1 \le x \le 2 \\ 2x - 4 & x > 2 \end{cases}$$

a. Compute $f(x)$ using a single `np.where` or `np.select` call.  
b. Find the indices and $x$-values where $f(x) > 3$.  
c. Compute $|f(x)|$ without using `np.abs` — use `np.where` only.  
d. Plot $f(x)$ and $|f(x)|$ on the same figure using Matplotlib.

---

**Exercise 5 — Linear Systems**  
Consider the 4×4 system $\mathbf{A}\mathbf{x} = \mathbf{b}$:

$$\mathbf{A} = \begin{pmatrix} 4 & -1 & 0 & 0 \\ -1 & 4 & -1 & 0 \\ 0 & -1 & 4 & -1 \\ 0 & 0 & -1 & 3 \end{pmatrix}, \quad \mathbf{b} = \begin{pmatrix} 15 \\ 10 \\ 10 \\ 10 \end{pmatrix}$$

a. Solve for $\mathbf{x}$ using `np.linalg.solve`.  
b. Verify the solution by computing $\|\mathbf{A}\mathbf{x} - \mathbf{b}\|$.  
c. Compute the condition number of $\mathbf{A}$.  
d. Find the eigenvalues of $\mathbf{A}$ and verify that all are positive (i.e., $\mathbf{A}$ is positive definite).

---

**Exercise 6 — Least Squares (Challenge)**  
The following (x, y) data are believed to follow the model $y = a \sin(x) + b \cos(x) + c$:

```python
x_data = np.linspace(0, 2 * np.pi, 20)
rng = np.random.default_rng(99)
y_data = 2.0 * np.sin(x_data) - 1.5 * np.cos(x_data) + 0.5 + rng.normal(0, 0.2, 20)
```

a. Build the design matrix $\mathbf{A}$ with three columns: $[\sin(x), \cos(x), \mathbf{1}]$.  
b. Use `np.linalg.lstsq` to estimate $a$, $b$, $c$. Compare to the true values $(2, -1.5, 0.5)$.  
c. Compute $R^2$ for the fit.  
d. Compute the singular values of $\mathbf{A}$ and use them to verify that the design matrix is full rank.

---

> **General tips:**
> - Use `np.random.default_rng(seed)` for reproducibility.
> - Before writing a loop, ask: *is there an `axis` argument or broadcasting trick that avoids it?*
> - Verify answers: `np.allclose`, `np.linalg.norm`, or manual spot-checks.

---

## Quick Reference

### Array Creation
| Function | Description |
|---|---|
| `np.array([1, 2, 3])` | From a Python list |
| `np.zeros(n)` / `np.ones(n)` | Array of zeros / ones |
| `np.arange(start, stop, step)` | Like `range()`, returns array |
| `np.linspace(a, b, N)` | N evenly spaced values from a to b |
| `np.logspace(a, b, N)` | N log-spaced values (10^a to 10^b) |
| `np.eye(n)` | n×n identity matrix |
| `np.full(shape, val)` | Array filled with a constant |

### Indexing
| Syntax | Description |
|---|---|
| `a[i]` | Element at index i |
| `a[i:j]` | Slice from i to j (exclusive) |
| `a[::k]` | Every k-th element |
| `a[::-1]` | Reversed |
| `M[r, c]` | Element at row r, column c |
| `M[:, c]` | Entire column c |
| `a[a > 0]` | Boolean filtering |
| `a[[0,2,4]]` | Fancy indexing |

### Methods (called on the array)
| Method | Description |
|---|---|
| `.sum(axis)` `.mean(axis)` `.std(ddof, axis)` | Aggregation |
| `.min()` `.max()` `.argmin()` `.argmax()` | Extremes and their locations |
| `.cumsum()` `.cumprod()` | Running totals |
| `.reshape(shape)` `.flatten()` `.ravel()` | Shape manipulation |
| `.sort()` | Sort in-place |
| `.astype(dtype)` `.copy()` | Type conversion, copying |
| `.T` | Transpose |

### Functions (called as `np.function(array)`)
| Function | Description |
|---|---|
| `np.exp` `np.log` `np.log10` | Exponential / logarithm |
| `np.sin` `np.cos` `np.tan` | Trigonometry (radians) |
| `np.sqrt` `np.abs` `np.sign` | Power, magnitude |
| `np.round` `np.floor` `np.ceil` `np.clip` | Rounding / clipping |
| `np.where(cond, x, y)` | Element-wise if-else |
| `np.where(cond)` | Indices where True |
| `np.sort` `np.argsort` `np.unique` | Sorting / search |
| `np.vstack` `np.hstack` `np.column_stack` | Combining arrays |
| `np.any` `np.all` `np.isnan` `np.isfinite` | Testing |

### Linear Algebra (`np.linalg`)
| Function | Description |
|---|---|
| `np.linalg.solve(A, b)` | Exact solution to Ax = b |
| `np.linalg.lstsq(A, b)` | Least-squares solution |
| `np.linalg.inv(A)` | Matrix inverse |
| `np.linalg.pinv(A)` | Moore-Penrose pseudo-inverse |
| `np.linalg.det(A)` | Determinant |
| `np.linalg.norm(v)` | Vector / matrix norm |
| `np.linalg.cond(A)` | Condition number |
| `np.linalg.eig(A)` | Eigenvalues and eigenvectors |
| `np.linalg.eigh(A)` | Same, for symmetric matrices |
| `np.linalg.svd(A)` | Singular value decomposition |
| `np.linalg.qr(A)` | QR decomposition |
| `A @ B` | Matrix multiplication |

## References
- NumPy documentation: https://numpy.org/doc/stable/
- Harris et al. (2020). Array programming with NumPy. *Nature*, 585, 357–362.
- Vanderplas, J. (2016). *Python Data Science Handbook*. O'Reilly. https://jakevdp.github.io/PythonDataScienceHandbook/